### ISSUE TITLE
CLI Implementation

### ISSUE THREAD

**Issue by devrimcavusoglu** [obss/jury#14]
CLI implementation for the package the read from txt files.

Draft Usage:
`jury evaluate --predictions predictions.txt --references references.txt`

[NLGEval](https://github.com/Maluuba/nlg-eval#standalone) uses single prediction and multiple references in a way that u specify multiple references.txt files for mulitple references, and like [this](https://github.com/Maluuba/nlg-eval#functional-api-for-the-entire-corpus) on API.

My idea is to have a single prediction and refenence file including multiple predictions or multiple references. In a single txt file, maybe we can use some sort of special separator like "`<sep>`" instead of a special char like `[",", ";", ":", "\t"]` maybe tab seperated would be OK. Wdyt ? @fcakyon @cemilcengiz

**Comment by fcakyon** [comment]
i prefer more intuitive separators instead of "" but really sure how we can implement single file cli usage. nlgevals multi-file cli usage and list based api usage seems to be very user-friendly to me.

maybe we can give folder directories as inputs in cli? `--prediction_folder dir/to/prediction/files --reference_folder dir/to/reference/files`

**Comment by devrimcavusoglu** [comment]
> i prefer more intuitive separators instead of ""

@fcakyon I didn't notice, but github interpreted `<sep>` as empty string :sweat_smile: , I've editted my comment.

**Comment by devrimcavusoglu** [comment]
@fcakyon @cemilcengiz wdyt about reading from tsv along with reading with multiple txt from folder ? tsv would ease the workload of user I think.

**Comment by fcakyon** [comment]
what is a tsv? a txt file with elements seperated by tabs or something else?

**Comment by devrimcavusoglu** [comment]
Exactly, tab seperated values. Here, is an [example](https://en.wikipedia.org/wiki/Tab-separated_values#Example) file.
