### ISSUE TITLE
demo notebook

### ISSUE THREAD

**Issue by fcakyon** [obss/jury#7]
we need to add demo notebook with some well known dataset and pretrained model from huggingface to showcase the usage of the `jury` package.

**Comment by sinanonur** [comment]
> we need to add demo notebook with some well known dataset and pretrained model from huggingface to showcase the usage of the `jury` package.

Preferably with a google collab link for convinience.

**Comment by fcakyon** [comment]
@sinanonur once we prepare a notebook, i can add the `open in colab` buttons with related links into both notebook and readme.
